# https://taskfile.dev

version: '3'

tasks:
  docs:
    dir: docs
    cmds:
      - pnpm install
      - pnpm dev
    silent: true
  build:
    cmds:
      - ./gradlew clean build
    silent: true
  run:
    cmds:
      - ./gradlew clean :core:runServer
    silent: true
  "run:shop":
    cmds:
      - ./gradlew clean :core:build --no-build-cache --rerun-tasks -x test
      - cp ./core/build/libs/core-*-all.jar ./addons/quickshop-hikari/run/plugins/
      - sleep 5 && echo "starting server..."
      - ./gradlew clean :addons:quickshop-hikari:runServer
    silent: true
  "run:quest":
    cmds:
      - ./gradlew clean :core:build --no-build-cache --rerun-tasks -x test
      - cp ./core/build/libs/core-*-all.jar ./addons/betonquest/run/plugins/
      - sleep 5 && echo "starting server..."
      - ./gradlew clean :addons:betonquest:runServer
  clear:
    cmds:
      - rm ./core/run/**/session.lock
      - rm ./addons/**/run/**/session.lock
    silent: true
  check:
    cmds:
      - ./gradlew clean ktlintFormat
      - task build
    silent: false

