openapi: '3.0.2'
info:
  title: "MineAuth"
  description: |
    This is the MineAuth API documentation.<br>
    This makes user access to self information on minecraft.
  license:
    name: CC0-1.0
    url: "https://creativecommons.org/publicdomain/zero/1.0/"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "Local server"
  - url: "https://api.example.com"
    description: "Production server"

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/token
          refreshUrl: /oauth2/token
          scopes:
            openid: Grants read access for OpenID Connect
            profile: Grants read access for my profile
            all: Grants read access for my resources

paths:
  /oauth2/userinfo:
    $ref: './paths/oauth2/userinfo.yml'
  /oauth2/revoke:
    $ref: './paths/oauth2/revoke.yml'
  /oauth2/introspect:
    $ref: './paths/oauth2/introspect.yml'
  /api/v1/commons/server/players:
    $ref: './paths/api/v1/common.yml'
  /api/v1/plugins/availableIntegrations:
    $ref: './paths/api/v1/plugins/main.yml'
  /api/v1/plugins/vault/balance/me:
    $ref: './paths/api/v1/plugins/vault/balance.yml'
  /api/v1/plugins/vault/send:
    $ref: './paths/api/v1/plugins/vault/send.yml'
  /api/v1/plugins/quickshop-hikari/users/{uuid}/shops:
    $ref: './paths/api/v1/plugins/quickshop-hikari/shop-list.yml'
  /api/v1/plugins/quickshop-hikari/shops/{shopId}:
    $ref: './paths/api/v1/plugins/quickshop-hikari/shop-info.yml'
  /api/v1/plugins/quickshop-hikari/shops/{shopId}/setting:
    $ref: './paths/api/v1/plugins/quickshop-hikari/shop-setting.yml'


