openapi: 3.1.0
info:
  title: "MineAuth"
  description: |
    This is the MineAuth API documentation.
    This makes user access to self information on minecraft.
  license:
    name: CC0-1.0
    url: "https://creativecommons.org/publicdomain/zero/1.0/"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "Local server"
  - url: "https://api.example.com"
    description: "Production server"

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/token
          scopes:
            read.*: Grants read access for my resources
            write.*: Grants write access for my resources

security:
  - oauth2: [ read.*, write.* ]

paths:
  - /oauth2/userinfo:
    get:
      summary: Get user information
      security:
        - oauth2: [ read ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The user UUID
                  username:
                    type: string
                    description: The user name
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
