site_name: MineAuth Docs
theme:
  name: material
  language: ja
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - render_swagger:
      allow_arbitrary_locations: true
  - search:
      lang: en
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
repo_url: https://github.com/morinoparty/MineAuth
repo_name: MineAuth
copyright: No Rights Reserved.
