name: deploy docs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: |
          pip install mkdocs-material
          pip install mkdocs-static-i18n[material]
          pip install mkdocs-render-swagger-plugin
      - run: git pull
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew :api:dokkaHtml

      - name: Copy dokkaHtml to docs
        run: cp -r ./api/build/dokka/html ./docs/docs/dokka

      - run: mkdocs gh-deploy --config-file ./docs/mkdocs.yml
